spring.application.name=musiccatalog

spring.datasource.url=jdbc:mysql://altaria.proxy.rlwy.net:53623/railway
spring.datasource.username=root
spring.datasource.password=wwkRxxXdJBIYayHsnPAdXfTBzrbgTFHe

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}

jwt.secret=ThisIsMySuperSecretKeyForMusicCatalogApplication123456789
jwt.expiration=86400000